#!/usr/bin/env python
'''
Convert a tile PNG and palette PNG to binary data to put in the game.

'''

import argparse

from PIL import Image

from ConversionLib.Snes import imgToSnesColourDepth, SnesPalette, SnesTile
from ConversionLib.image_cropper import get_tiles

def writeAsmFile(path: str, tileBinPath: str, palettePath: str):
    symname=path.rsplit('/')[-1].replace('.s','')
    lines=[
        '    ; Autogenerated by tileimg_to_bin',
        f'    .section "_rodata.huge.{symname}"',
        f'    .global _{symname}_tiles',
        f'    .global _{symname}_tiles_size',
        f'    .global _{symname}_palette',
        f'    .global _{symname}_palette_size',
        f'_{symname}_tiles:',
        f'    .incbin "{symname}.tiles.bin"',
        f'_{symname}_tiles_end:',
        f'    _{symname}_tiles_size = _{symname}_tiles_end - _{symname}_tiles',
        f'_{symname}_palette:',
        f'    .incbin "{symname}.pal.bin"',
        f'_{symname}_palette_end:',
        f'    _{symname}_palette_size = _{symname}_palette_end - _{symname}_palette',
        '    ; End of generated content',
        ''
    ]
    with open(path, 'w') as f:
        f.write('\n'.join(lines))

def writeHeaderFile(path: str, tileDataSize: int, paletteDataSize: int):
    headerPath = path.replace('.s', '.h')
    symname=path.rsplit('/')[-1].replace('.s','')
    lines=[
        '// Autogenerated by tileimg_to_bin',
        '#include <stdint.h>',
        f'extern uint16_t {symname}_tiles[{tileDataSize//2}];',
        f'extern uint16_t {symname}_palette[{paletteDataSize//2}];',
        '// End of generated content',
        ''
    ]
    with open(headerPath, 'w') as f:
        f.write('\n'.join(lines))

def output(path: str, tileData: bytes, paletteData: bytes):
    tileBinPath = path.replace('.s', '.tiles.bin')
    palettePath = path.replace('.s', '.pal.bin')
    with open(tileBinPath, 'wb') as f:
        f.write(tileData)
    with open(palettePath, 'wb') as f:
        f.write(paletteData)
    writeAsmFile(path, tileBinPath, palettePath)
    writeHeaderFile(path, len(tileData), len(paletteData))

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('inputTileFile', metavar='<input.png>', type=str, help="Input PNG file containing tiles to convert")
    parser.add_argument('inputPaletteFile', metavar='<input_palette.png>', type=str, help="Input PNG file containing the palette to use with the tile PNG")
    parser.add_argument('outputFile', metavar='<output.s>', type=str, help="Path to output .s file")
    parser.add_argument('--bpp', type=int, help="Graphics colour depth (2, 4, or 8)")
    args = parser.parse_args()
    with ( Image.open(args.inputTileFile) as tileImg,
           Image.open(args.inputPaletteFile) as paletteImg ):
        tileImg = imgToSnesColourDepth(tileImg)
        paletteImg = imgToSnesColourDepth(paletteImg)
    palette = SnesPalette.from_image(paletteImg, bpp=args.bpp)
    tileImgs = get_tiles(tileImg, 8)
    tileData = []
    for idx, tileImg in enumerate(tileImgs):
        tile = SnesTile.from_image(tileImg, palette, index=idx)
        tileData.append(tile.to_bytes())
    tileData = b''.join(tileData)
    paletteData = palette.to_bytes()
    assert len(tileData) % 2 == 0
    assert len(paletteData) % 2 == 0
    output(args.outputFile, tileData, paletteData)

if __name__ == '__main__':
    main()
